### ISSUE TITLE
RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by andrewsilver1997** [graphdeco-inria/gaussian-splatting#1220]
Hi, 

I'm running 3DGS on my custom dataset. I organized the dataset in the same style of nerf synthetic dataset. then I have the following problem:

```
Found transforms_train.json file, assuming Blender data set! [02/05 09:40:02]
Reading Training Transforms [02/05 09:40:02]
Reading Test Transforms [02/05 09:40:04]
Generating random point cloud (100000)... [02/05 09:40:04]
Loading Training Cameras [02/05 09:40:05]
Loading Test Cameras [02/05 09:40:06]
Number of points at initialisation :  100000 [02/05 09:40:06]
Training progress:   0%|                                        | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 282, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 142, in training
    loss.backward()
  File "/home/zikai/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zikai/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Training progress:   0%|                                        | 0/30000 [00:00<?, ?it/s]
```

could you help me with that? Thank you

**Comment by andrewsilver1997** [comment]
And FYI, for nerf synthetic dataset the code is runnable, so I found it a bit weird .....

**Comment by BitCalSaul** [comment]
@andrewsilver1997 Hi i found it works well for one dataset while error for another. I'm wondering did you fix it?

**Comment by andrewsilver1997** [comment]
Hi @BitCalSaul,

yes I solved it. My issue was that my camera pose had some conflicts with 3DGS coodinates. so you better carefully check the way you recorded your camera pose ;)
