### ISSUE TITLE
Vram issues with low input count

### ISSUE THREAD

**Issue by DrTheteSigma** [graphdeco-inria/gaussian-splatting#1242]
Hello, 

I am reaching my 16gb ram limit on my tesla t4 with just loading 60 images of 1200x1600 resolution. I am finding it odd that some people can load thousands of images with no issues. Here are my training settings.

  run_command([
        "python", os.path.join(script_dir, "train.py"),
        "--iterations", "30000",
        "-s", local_tmp_dir,
        "--test_iterations", "-1",
        "--data_device", "cpu",  # Use CPU for data device

    ])

Error shown

orch.OutOfMemoryError: CUDA out of memory. Tried to allocate 950.00 MiB. GPU 0 has a total capacity of 14.57 GiB of which 680.75 MiB is free. Including non-PyTorch memory, this process has 13.90 GiB memory in use. Of the allocated memory 9.58 GiB is allocated by PyTorch, and 4.16 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Training progress:  10%|▉         | 2200/23000 [12:06<1:54:29,  3.03it/s, Loss=0.1577509, Depth Loss=0.0000000]
An error occurred while processing session 1268348509db4415b378e62386c33e96: Command '['python', '/home/ubuntu/splats/gaussian-splatting/train.py', '--iterations', '30000', '--checkpoint_iterations', '30000', '--start_checkpoint', '/home/ubuntu/splats/gaussian-splatting/output/8a05def5-6/chkpnt7000.pth', '-s', '/home/ubuntu/splats/gaussian-splatting/tmp', '--data_device', 'cpu']' returned non-zero exit status 1.

**Comment by utadluis** [comment]
Did you find a solution or any workaround that helped reduce the memory usage or avoid the CUDA out of memory error?

**Comment by abolhoseinisina** [comment]
@DrTheteSigma @utadluis 
Try changing the `resolution`. It solved my problem by setting it to 2.
`python train.py -s [path] --resolution 2`
