### ISSUE TITLE
CUBLAS_STATUS_NOT_SUPPORTED when calling cublasSgemmStridedBatched

### ISSUE THREAD

**Issue by vvhitedog** [graphdeco-inria/gaussian-splatting#184]
I came across this issue using the recommended instructions as per the readme in the main github repository. 

## Steps to reproduce

Follow the instructions to load the default conda env, namely

```
conda env create --file environment.yml 
conda activate gaussian_splatting
```

Then attempt to train, resulting in error:
```
python train.py -s tandt/train/                                                                                                                                                                                                                                                                
Optimizing                                                                                                                                                                                                                                                                                                                                                 
Output folder: ./output/061dc0a9-1 [09/09 12:35:18]                                                                                                                                                                                                                                                                                                        
Tensorboard not available: not logging progress [09/09 12:35:18]                                                                                                                                                                                                                                                                                           
Reading camera 301/301 [09/09 12:35:20]                                                                                                                                                                                                                                                                                                                    
Converting point3d.bin to .ply, will happen only the first time you open the scene. [09/09 12:35:20]                                                                         
Loading Training Cameras [09/09 12:35:21]                                                                                                                                    
Traceback (most recent call last):                                                                                                                                           
  File "train.py", line 216, in <module>                                                                                                                                                                                                                                                                                                                   
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training                                                                                                                                      
    scene = Scene(dataset, gaussians)                                                                                                                                        
  File "/staging/tbdel/splatting/gaussian-splatting/scene/__init__.py", line 73, in __init__                                                                                 
    self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale, args)                                                        
  File "/staging/tbdel/splatting/gaussian-splatting/utils/camera_utils.py", line 58, in cameraList_from_camInfos                                                                                                                                                                                                                                           
    camera_list.append(loadCam(args, id, c, resolution_scale))                                                                                                                                                                                                                                                                                             
  File "/staging/tbdel/splatting/gaussian-splatting/utils/camera_utils.py", line 52, in loadCam                                                                                                                                                                                                                                                            
    image_name=cam_info.image_name, uid=id, data_device=args.data_device)                                                                                                                                                                                                                                                                                  
  File "/staging/tbdel/splatting/gaussian-splatting/scene/cameras.py", line 56, in __init__                                                                                                                                                                                                                                                                
    self.full_proj_transform = (self.world_view_transform.unsqueeze(0).bmm(self.projection_matrix.unsqueeze(0))).squeeze(0)                                                                                                                                                                                                                                
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)` 
```

## Possible fix

This seems to be a bug that is only present in the particular configuration given by the set of package versions specified in the `environment.yml`.  Applying the following diff and rerunning the steps above results in training working as expected.

```
diff --git a/environment.yml b/environment.yml
index b17a50f..4a45644 100644
--- a/environment.yml
+++ b/environment.yml
@@ -4,7 +4,7 @@ channels:
   - conda-forge
   - defaults
 dependencies:
-  - cudatoolkit=11.6
+  - cudatoolkit=11.3
   - plyfile=0.8.1
   - python=3.7.13
   - pip=22.3.1
@@ -14,4 +14,4 @@ dependencies:
   - tqdm
   - pip:
     - submodules/diff-gaussian-rasterization
     - submodules/simple-knn
```

## Possible reason for issue

This issue appears to be possibly hardware/cuda-version/torch-version specific. It appears that the call to `cublasSgemmStridedBatched` may use different heuristics depending on available hardware and versions of software/drivers. 

Previous reports of this issue lead to patches within Cuda BLAS. See for example https://stackoverflow.com/a/51749792.

However, this error can also be caused by incorrect shapes/sizing passed to the GEMM procedure. In this case, because a version change fixed the issue (at least for this instance) it's unlikely to be an issue with implementation.

**Comment by blacksungrass** [comment]
In the possible fix proposed by @vvhitedog , that patch file seems malformed, so I just edit environment.yaml and changed cudatoolkit version from 11.6 to 11.3 manually, and that works for me. Thanks a lot.

**Comment by HalvesChen** [comment]
I just use pip to install torch and torchvision, and that works for me.Thanks a lot.
