### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by astaikosvz** [graphdeco-inria/gaussian-splatting#222]
When trying to run training.py I keep getting the error - RuntimeError: CUDA error: an illegal memory access was encountered immediately.  Running on Windows 11, CUDA 11.8.

**Comment by grgkopanas** [comment]
Please provide the git SHA/commit and if you changed anything in the code
together with what dataset you used.

Thanks :)

**Comment by XDzzzzzZyq** [comment]
I didn't change any code and my dataset is a sequence of 200 frames of 1920*1080px jpg images

**Comment by astaikosvz** [comment]
@grgkopanas Here is the commit I am using: 6cf495fe4abeb57c3528a5eb3366b9ff17ab9c50. I am using Jon Stephens fork.  I have not made any code changes.  I created a dataset based on his tutorial video using COLMAP. It has 164 images 1080*1920 resolution

**Comment by grgkopanas** [comment]
Hi, 

This seems to be a commit from a fork, I apologize but we cannot support that. We even struggle to support our original repo since we are just an academic lab and only a couple of people looking at issues.

Best,
George

**Comment by XDzzzzzZyq** [comment]
I tried using 720p images as the dataset (without using the command), and this problem was solved. I believe there are two possible reasons: 

1. Out of Memory, but train.py didn't throw this error explicitly
2. Something wrong with convert.py. After a double check with my training process, I noticed there were only 10 cameras available for the 1080p dataset.
