### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by knightchrism** [graphdeco-inria/gaussian-splatting#394]
Having memory issues. Can I try anything to get past this error?

(gaussian_splatting) C:\Users\Administrator\gaussian-splatting>python train.py -s C:\Users\Administrator\gaussian-splatting\data\Site_1
Optimizing
Output folder: ./output/d6bccac4-6 [26/10 11:28:55]
Tensorboard not available: not logging progress [26/10 11:28:55]
Reading camera 3311/3311 [26/10 11:29:34]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [26/10 11:29:34]
Loading Training Cameras [26/10 11:29:48]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [26/10 11:29:48]
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Users\Administrator\gaussian-splatting\scene\__init__.py", line 73, in __init__
    self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale, args)
  File "C:\Users\Administrator\gaussian-splatting\utils\camera_utils.py", line 58, in cameraList_from_camInfos
    camera_list.append(loadCam(args, id, c, resolution_scale))
  File "C:\Users\Administrator\gaussian-splatting\utils\camera_utils.py", line 52, in loadCam
    image_name=cam_info.image_name, uid=id, data_device=args.data_device)
  File "C:\Users\Administrator\gaussian-splatting\scene\cameras.py", line 46, in __init__
    self.original_image *= torch.ones((1, self.image_height, self.image_width), device=self.data_device)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.99 GiB total capacity; 21.23 GiB already allocated; 0 bytes free; 21.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by yangqinhui0423** [comment]
Hey! Have you solved this problem? I meet the same question today.
_RuntimeError: CUDA out of memory. Tried to allocate 1.35 GiB (GPU 0; 6.00 GiB total capacity; 1.84 GiB already allocated; 0 bytes free; 5.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF_

**Comment by yalcincenik** [comment]
RuntimeError: CUDA out of memory how did you fix it? @jkbkcr  @yangqinhui0423

**Comment by jkbkcr** [comment]
I just updated the graphic card drivers (I am using RTX 4060) and it is working well, thanks @yangqinhui0423 
@fifi1ous @yalcincenik @knightchrism

**Comment by knightchrism** [comment]
I never did figure this problem out. I ended up using less photos and it worked. I also used the reduce resolution flag and it worked as well. Quality was not great. Also I was using a A5000 card. Going to try again with a A6000 Ada card when I get one.
    On Friday, December 1, 2023 at 06:00:29 AM EST, jkbkcr ***@***.***> wrote:  
 
 


I just updated the graphic card drivers (I am using RTX 4060) and it is working well, thanks @yangqinhui0423
@fifi1ous @yalcincenik @knightchrism
