### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by tingzhongyue** [graphdeco-inria/gaussian-splatting#660]
Hi,
Thanks a lot for sharing your great work. 
I've built the environment properly and while running the DTU dataset, I try to use the rasterization to render the image. But I got following error: 
Traceback (most recent call last):
  File "train.py", line 225, in <module>
    main()
  File "train.py", line 150, in main
    train_epoch(config,
  File "/root/autodl-tmp/idea/scripts/trainer.py", line 94, in train_epoch
    image = render(view, pc, background, config, device)["render"].cuda()
  File "/root/autodl-tmp/idea/gaussian_renderer/__init__.py", line 80, in render
    "visibility_filter" : radii > 0,
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Any idea how to resolve? 

My system & settings:
RTX3090
Linux 20.04

I hope I can get some solution for this problem!

Thank you.

**Comment by gaetan-landreau** [comment]
Hi, 

Check out this issue and the corresponding PR that is linked [here](https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620) . Should help :)

**Comment by MouseChannel** [comment]
same
RTX3090
Linux 20.04

same error
 has any solution yet?
try ![here](https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620) but not work

**Comment by MouseChannel** [comment]
> Hi, Thanks a lot for sharing your great work. I've built the environment properly and while running the DTU dataset, I try to use the rasterization to render the image. But I got following error: Traceback (most recent call last): File "train.py", line 225, in main() File "train.py", line 150, in main train_epoch(config, File "/root/autodl-tmp/idea/scripts/trainer.py", line 94, in train_epoch image = render(view, pc, background, config, device)["render"].cuda() File "/root/autodl-tmp/idea/gaussian_renderer/**init**.py", line 80, in render "visibility_filter" : radii > 0, RuntimeError: CUDA error: an illegal memory access was encountered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. Any idea how to resolve?
> 
> My system & settings: RTX3090 Linux 20.04
> 
> I hope I can get some solution for this problem!
> 
> Thank you.

have you fix it up?

**Comment by tingzhongyue** [comment]
> > 您好，非常感谢您分享您的出色工作。我已经正确构建了环境，并且在运行 DTU 数据集时，我尝试使用光栅化来渲染图像。但我收到以下错误： Traceback (most最近一次调用最后): File "train.py", line 225, in main() File "train.py", line 150, in main train_epoch(config, File "/root/autodl -tmp/idea/scripts/trainer.py"，第 94 行，在 train_epoch 中 image = render(view, pc, background, config, device)["render"].cuda() 文件 "/root/autodl-tmp/idea /gaussian_renderer/ **init** .py”，第 80 行，渲染“visibility_filter”：半径 > 0，运行时错误：CUDA 错误：遇到非法内存访问编译以`TORCH_USE_CUDA_DSA`启用设备端断言。知道如何解决吗？
> > 我的系统和设置：RTX3090 Linux 20.04
> > 我希望我能为这个问题找到一些解决方案！
> > 谢谢。
> 
> 你修好了吗？

Are you using the source code? The reason I had problems was that I got the degree of the spherical harmonics wrong.

**Comment by JrMeng0312** [comment]
> same RTX3090 Linux 20.04
> 
> same error has any solution yet? try ![here](https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620) but not work

I meet the same problem. Have you fixed it up?

**Comment by MilesCool** [comment]
Perhaps just ensure that all the parameters passed to gaussian_renderer is on the same device, i also got this error when i tried to modify something, finally i found some parameters is on cpu, and i changed it to cuda, everything worked.

**Comment by tlxhlll** [comment]
> > same RTX3090 Linux 20.04
> > same error has any solution yet? try ![here](https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620) but not work
> 
> I meet the same problem. Have you fixed it up?

I have solved this problem. you just need to install the version of [diff-gaussian-rasterization](https://github.com/computational-imaging/GSM/tree/main/submodules/diff-gaussian-rasterization)

**Comment by tlxhlll** [comment]
I have solved this problem. you just need to install the version of [diff-gaussian-rasterization](https://github.com/computational-imaging/GSM/tree/main/submodules/diff-gaussian-rasterization)

**Comment by this233** [comment]
> Perhaps just ensure that all the parameters passed to gaussian_renderer is on the same device, i also got this error when i tried to modify something, finally i found some parameters is on cpu, and i changed it to cuda, everything worked.

thank you! you are right! it work

**Comment by this233** [comment]
> Perhaps just ensure that all the parameters passed to gaussian_renderer is on the same device, i also got this error when i tried to modify something, finally i found some parameters is on cpu, and i changed it to cuda, everything worked.

thank you ! it work!

**Comment by cat-fish-yu** [comment]
> > > 您好，非常感谢您分享您的出色工作。我已经正确构建了环境，并且在运行 DTU 数据集时，我尝试使用光栅化来渲染图像。但我收到以下错误： Traceback (most最近一次调用最后): File "train.py", line 225, in main() File "train.py", line 150, in main train_epoch(config, File "/root/autodl -tmp/idea/scripts/trainer.py"，第 94 行，在 train_epoch 中 image = render(view, pc, background, config, device)["render"].cuda() 文件 "/root/autodl-tmp/idea /gaussian_renderer/ **init** .py”，第 80 行，渲染“visibility_filter”：半径 > 0，运行时错误：CUDA 错误：遇到非法内存访问编译以`TORCH_USE_CUDA_DSA`启用设备端断言。知道如何解决吗？
> > > 我的系统和设置：RTX3090 Linux 20.04
> > > 我希望我能为这个问题找到一些解决方案！
> > > 谢谢。
> > 
> > 
> > 你修好了吗？
> 
> Are you using the source code? The reason I had problems was that I got the degree of the spherical harmonics wrong.你在使用源代码吗？我有问题的原因是，我把球谐函数的次数弄错了。

Hi, how did you solve it? I have the same problem, but  other methods  didn't work.

**Comment by cat-fish-yu** [comment]
> > Hi, Thanks a lot for sharing your great work. I've built the environment properly and while running the DTU dataset, I try to use the rasterization to render the image. But I got following error: Traceback (most recent call last): File "train.py", line 225, in main() File "train.py", line 150, in main train_epoch(config, File "/root/autodl-tmp/idea/scripts/trainer.py", line 94, in train_epoch image = render(view, pc, background, config, device)["render"].cuda() File "/root/autodl-tmp/idea/gaussian_renderer/**init**.py", line 80, in render "visibility_filter" : radii > 0, RuntimeError: CUDA error: an illegal memory access was encountered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. Any idea how to resolve?嗨，非常感谢分享您的伟大工作.我已经正确地构建了环境，在运行DTU数据集时，我尝试使用光栅化来渲染图像。但我得到了以下错误：Traceback（most recent call last）：File“train.py“，line 225，in main（）File“train.py”，line 150，in main train_epoch（config，File“/root/autodl-tmp/idea/scripts/trainer.py“，line 94，in train_epoch image = render（view，pc，background，config，device）[“render”].cuda（）File“/root/autodl-tmp/idea/gaussian_renderer/init.py“，line 80，in render“visibility_filter”：radius> 0，RuntimeError：CUDA error：an illegal memory access was encountered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.有办法解决吗？
> > My system & settings: RTX3090 Linux 20.04我的系统和设置：RTX 3090 Linux 20.04 
> > I hope I can get some solution for this problem!我希望我能找到解决这个问题的方法！ 
> > Thank you. 谢谢
> 
> have you fix it up?你修好了吗？

Have you fix it up?

**Comment by Zhiyuan-Yuan** [comment]
> > > Hi, Thanks a lot for sharing your great work. I've built the environment properly and while running the DTU dataset, I try to use the rasterization to render the image. But I got following error: Traceback (most recent call last): File "train.py", line 225, in main() File "train.py", line 150, in main train_epoch(config, File "/root/autodl-tmp/idea/scripts/trainer.py", line 94, in train_epoch image = render(view, pc, background, config, device)["render"].cuda() File "/root/autodl-tmp/idea/gaussian_renderer/**init**.py", line 80, in render "visibility_filter" : radii > 0, RuntimeError: CUDA error: an illegal memory access was encountered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. Any idea how to resolve?嗨，非常感谢分享您的伟大工作.我已经正确地构建了环境，在运行DTU数据集时，我尝试使用光栅化来渲染图像。但我得到了以下错误：Traceback（most recent call last）：File“train.py“，line 225，in main（）File“train.py”，line 150，in main train_epoch（config，File“/root/autodl-tmp/idea/scripts/trainer.py“，line 94，in train_epoch image = render（view，pc，background，config，device）[“render”].cuda（）File“/root/autodl-tmp/idea/gaussian_renderer/init.py“，line 80，in render“visibility_filter”：radius> 0，RuntimeError：CUDA error：an illegal memory access was encountered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.有办法解决吗？
> > > My system & settings: RTX3090 Linux 20.04我的系统和设置：RTX 3090 Linux 20.04
> > > I hope I can get some solution for this problem!我希望我能找到解决这个问题的方法！
> > > Thank you. 谢谢
> > 
> > 
> > have you fix it up?你修好了吗？
> 
> Have you fix it up?

have you solve it?

**Comment by PAIGUI** [comment]
> 也许只是确保传递给 gaussian_renderer 的所有参数都在同一设备上，当我尝试修改某些内容时也遇到了这个错误，最后我发现一些参数在 cpu 上，我把它改成了 cuda，一切正常。

Hello, can you talk about the specific part that was changed?

**Comment by SleepTight-Cat** [comment]
To add to the discussion, I encountered the same error earlier, and in my case, it was caused by an incorrect input shape to the rasterizer. This led to incorrect outputs—including the radii. I had been modifying the code a bit, which is likely what introduced the issue.

Someone above mentioned fixing the SH degree, which is somewhat similar to my situation—as incorrect SH settings can result in a mismatch in the feature_rest dimensions.

**Comment by dadaaichifan** [comment]
> 也许只是确保传递给 gaussian_renderer 的所有参数都在同一设备上，当我尝试修改某些内容时也遇到了这个错误，最后我发现一些参数在 cpu 上，我把它改成了 cuda，一切正常。

May I ask how you operated? It seems I have encountered this problem as well.
