### ISSUE TITLE
Issue with Simple-KNN's distCUDA2 function

### ISSUE THREAD

**Issue by PeizhiYan** [graphdeco-inria/gaussian-splatting#695]
I found a strange problem when using the ```distCUDA2``` function. If the input tensor is on my second GPU ```cuda:1```, this function will cause the following error (please also see attached screenshot):
>terminate called after throwing an instance of 'thrust::system::system_error'
>  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
> Aborted (core dumped)

<img width="605" alt="image" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/34731246/924183b4-18d4-4049-b06c-3673c67d3976">

However, it works fine when I use ```cuda:0```.

**Comment by PeizhiYan** [comment]
I think I solved the problem :)

Just need to set the CUDA device to the same as the input tensor's:

```

#include "spatial.h"
#include "simple_knn.h"

#include <cuda_runtime.h>  // Include the CUDA runtime header for cudaSetDevice()

torch::Tensor
distCUDA2(const torch::Tensor& points)
{
  const int P = points.size(0);

  // Determine which device the tensor is on
  auto device = points.device();
  int device_index = device.index(); // Get the index of the device

  // Set the current CUDA device to the device where 'points' is located
  cudaSetDevice(device_index);

  auto float_opts = points.options().dtype(torch::kFloat32);
  torch::Tensor means = torch::full({P}, 0.0, float_opts);
  
  SimpleKNN::knn(P, (float3*)points.contiguous().data<float>(), means.contiguous().data<float>());

  return means;
}
```
