### ISSUE TITLE
Cuda out of memory when calling the distCUDA2

### ISSUE THREAD

**Issue by M1sak1-Mei** [graphdeco-inria/gaussian-splatting#740]
At the same env，code could run with 3090, but when using Tesla V100 32g
File "***/gaussian-splatting/scene/gaussian_model.py", line 134, in create_from_pcd
    dist2 = torch.clamp_min(distCUDA2(torch.from_numpy(np.asarray(pcd.points)).float().cuda()), 0.0000001)
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory
python-BaseException 

3090 is using ubuntu22.04, V100 is ubuntu20.04
I have tried reinstall simple-knn,it does not work

**Comment by wb014** [comment]
same situation here

**Comment by M1sak1-Mei** [comment]
我把cudasdk，conda什么的都重装，环境重新配置之后就好了
My issus fixed after I reinstalled everything

**Comment by altaykacan** [comment]
Hey!

I had the same problem and it somehow got fixed on its own. I couldn't figure out why that was happening but I think it has something to do with CUDA versions and the specific GPU you're using. My problem thankfully fixed itself magically but I have a couple of suggestions.

Maybe you can try deleting the build directory that gets created in your `submodules/simple-knn` directory and try reinstalling via pip. I guess some executables created on a different GPU when you first compile it might cause issues on other GPUs. 

Also according to [this](https://github.com/graphdeco-inria/gaussian-splatting/issues/292) issue, the only place `distCUDA2` and simple-knn are used is to calculate the initial scale values of the gaussians. The answers to the issue have code examples on how to do the exact same thing with scipy without using simple-knn at all so you can basically remove that line of code.

I hope this helps, good luck!

**Comment by yutiaoyi** [comment]
I met the same problem and I have solved it.
You can delete the build directory under **submodules/simple-knn**, and try reinstalling it via pip.
It's a temp directory for build but you may remain some files from your 4090.

I hope thhis helps, good luck!

**Comment by pzpzpzp3** [comment]
same issue on h100s. deleting build and re-installing didn't help

**Comment by yutiaoyi** [comment]
> h100s 上也有同样的问题。删除构建目录并重新安装并没有帮助。

Hi, I met the same problem on h100s, did you solve this problem? Could you provide the solution if you have solve the problem, thanks a lot!

**Comment by yutiaoyi** [comment]
> same situation here, simple-knn doesn't work with a800 but works fine with 3090

Hi, did you solve this problem on A800? If did, could you provide the solution? Thanks a lot!!

**Comment by fanld** [comment]
参考这篇文章。https://blog.gitcode.com/91693e7d6c16c67b2388529e3f944c91.html
