### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by baoachun** [graphdeco-inria/gaussian-splatting#781]
I have identified that the `identifyTileRanges` function is causing the issue, but I'm not quite sure how to resolve it. Do you have any constructive suggestions?
https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/rasterizer_impl.cu#L116

**Oddly, I didn't encounter any issues when I directly loaded the saved input parameters for rendering.**
[dump_file.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/15159771/dump_file.zip)

```
pytorch 1.13.1
cuda 11.4
A100 SXM4 80G
```

After several days of debugging, I found that the concatenation of keys might have caused anomalies, leading to memory errors. By storing them separately instead of concatenating, this issue was resolved. However, another exception occurred in the `FORWARD::render` function, and the problem couldn't be reproduced with the parameters saved in debug mode.

**Comment by PanagiotisP** [comment]
Does it happen on the first iteration or later on? Can you check whether you have nans on any tensors fed to the rasterisation function?

**Comment by baoachun** [comment]
@PanagiotisP  Yes, the issue tends to occur after iterating hundreds of times, but sometimes it may take thousands of iterations to appear. I have checked the input parameters and have not found any NaN values. However, I noticed that the error occurs because `currtile` or `prevtile` exceeds the length of `ranges`, resulting in a memory out-of-bounds issue. At this point, `currtile` or `prevtile` are very large strange numbers, such as `prevtile=3210786815` and `currtile=1072937470`. Do you have any insights on this?

**Comment by PanagiotisP** [comment]
No, I'm sorry. I'm not very familiar with the tiling procedure, so NaN was my best bet. In your place, I think, I would also check if extremely big scale values appear for some reason (e.g. due to a regularisation term gone bad). But other than that, your guess is as good as mine

**Comment by Devlee247** [comment]
@baoachun Did you solve this problem? I also got a very large strange numbers (currtile, prevtile).

**Comment by baoachun** [comment]
@Devlee247 Yes, I changed the concatenation operation of ID and depth to store them separately, and that bug is fixed. However, I still encounter errors in the `FORWARD::render` function, and I suspect there are other unresolved issues in the `FORWARD::render` function.

**Comment by Devlee247** [comment]
@baoachun Thank you for sharing, I also fixed via adding torch.cuda.empty_cache() in the forward function. (GaussianSplatting pytorch Class)

**Comment by baoachun** [comment]
@Devlee247 Thank you for sharing, unfortunately, this method does not solve my problem.

**Comment by huahangc** [comment]
@PanagiotisP How to solve this problem which the gaussian primitives attributions turn to be `Nan` when I train for thousands iterations? And I check the Nan value and turn all nan to 0, but in the rest iterations, all the loss come to be nan.

**Comment by RaymondJiangkw** [comment]
Perhaps check `my_radius`. Replacing the `float my_radius = ceil(...)` with `int my_radius = max(ceil(...), 1)` might help.

**Comment by manurare** [comment]
> @PanagiotisP Yes, the issue tends to occur after iterating hundreds of times, but sometimes it may take thousands of iterations to appear. I have checked the input parameters and have not found any NaN values. However, I noticed that the error occurs because `currtile` or `prevtile` exceeds the length of `ranges`, resulting in a memory out-of-bounds issue. At this point, `currtile` or `prevtile` are very large strange numbers, such as `prevtile=3210786815` and `currtile=1072937470`. Do you have any insights on this?

Hi, I am having the same problem. I found out that in my input tensors there are no NaN values, but there are Inf values and this is what causing the error. Do you know if in your input tensors you had Inf values?

**Comment by torracxiaokeai** [comment]
I meet same error with you, but the methods under this issue cannot address my porblem.
I wonder that how can I identified my error?

**Comment by baoachun** [comment]
> > @PanagiotisP Yes, the issue tends to occur after iterating hundreds of times, but sometimes it may take thousands of iterations to appear. I have checked the input parameters and have not found any NaN values. However, I noticed that the error occurs because `currtile` or `prevtile` exceeds the length of `ranges`, resulting in a memory out-of-bounds issue. At this point, `currtile` or `prevtile` are very large strange numbers, such as `prevtile=3210786815` and `currtile=1072937470`. Do you have any insights on this?
> 
> @baoachun I am having the same problem. I found out that in my input tensors there are no NaN values, but there are Inf values and this is what causing the error. Do you know if in your input tensors you had Inf values?
> 
> EDIT:
> 
> I did some debug on this. Values that are Inf (for example scales in my case) cause NaN radius. However, the gaussians with NaN radius are nonetheless added as rendered gaussians (`num_rendered`) since there is no check for NaNs in [`preprocess`](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/rasterizer_impl.cu#L248). Next, we will reallocate `num_rendered` **uninitialized** memory for the `binningState` object.
> 
> When duplicating keys, we iterate over [all gaussians with positive radius](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/rasterizer_impl.cu#L85) and assign values to the keys and values arrays which are arrays of `num_rendered` size from `binningState`. Remember that NaN gaussians **are rendered gaussians** but they don't get any key/value because their radii is not positive and thus, **their key and value are never assigned: their values come from uninitialized memory**. This causes the illegal memory access in some cases. This is why the error occurs randomly, because unitialized memory is unpredictable and can have any value at any time.

It seems this could be the reason. I also noticed large strange numbers, possibly because the memory was not explicitly initialized, but I didn't continue investigating further. I have been using the gsplat package, which doesn't throw an error when NaN or inf values appear, but the rendering result is incorrect. In such cases, you need to debug and check manually. For those encountering similar issues in the future, it might be helpful to print out the value of the scale attribute. I suspect that the problem might be caused by the scale attribute having inf values.

**Comment by smart4654154** [comment]
> `gsplat` package

gsplat package has the same error,do you know how to solve it?thank you 
https://github.com/nerfstudio-project/gsplat/issues/341

**Comment by VincentLimbach** [comment]
> > @PanagiotisP Yes, the issue tends to occur after iterating hundreds of times, but sometimes it may take thousands of iterations to appear. I have checked the input parameters and have not found any NaN values. However, I noticed that the error occurs because `currtile` or `prevtile` exceeds the length of `ranges`, resulting in a memory out-of-bounds issue. At this point, `currtile` or `prevtile` are very large strange numbers, such as `prevtile=3210786815` and `currtile=1072937470`. Do you have any insights on this?
> 
> @baoachun I am having the same problem. I found out that in my input tensors there are no NaN values, but there are Inf values and this is what causing the error. Do you know if in your input tensors you had Inf values?
> 
> EDIT:
> 
> I did some debug on this. Values that are Inf (for example scales in my case) cause NaN radius. However, the gaussians with NaN radius are nonetheless added as rendered gaussians (`num_rendered`) since there is no check for NaNs in [`preprocess`](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/rasterizer_impl.cu#L248). Next, we will reallocate `num_rendered` **uninitialized** memory for the `binningState` object.
> 
> When duplicating keys, we iterate over [all gaussians with positive radius](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/rasterizer_impl.cu#L85) and assign values to the keys and values arrays which are arrays of `num_rendered` size from `binningState`. Remember that NaN gaussians **are rendered gaussians** but they don't get any key/value because their radii is not positive and thus, **their key and value are never assigned: their values come from uninitialized memory**. This causes the illegal memory access in some cases. This is why the error occurs randomly, because unitialized memory is unpredictable and can have any value at any time.

This helped a lot! Apparently, you get these memory errors for a number of incorrect inputs. Notably, I created my own masks and passed values between 0 and 255 instead of 0 and 1. I didn't consider that this could be the problem until I saw your post. Thanks a lot!

**Comment by smart4654154** [comment]
> > > @PanagiotisP Yes, the issue tends to occur after iterating hundreds of times, but sometimes it may take thousands of iterations to appear. I have checked the input parameters and have not found any NaN values. However, I noticed that the error occurs because `currtile` or `prevtile` exceeds the length of `ranges`, resulting in a memory out-of-bounds issue. At this point, `currtile` or `prevtile` are very large strange numbers, such as `prevtile=3210786815` and `currtile=1072937470`. Do you have any insights on this?是的，问题通常在迭代数百次后出现，但有时可能需要数千次迭代才会出现。我已经检查了输入参数，没有发现任何 NaN 值。然而，我注意到错误发生是因为 `currtile` 或 `prevtile` 超过了 `ranges` 的长度，导致内存越界问题。此时， `currtile` 或 `prevtile` 是非常大的奇怪数字，例如 `prevtile=3210786815` 和 `currtile=1072937470` 。您对此有何见解？
> > 
> > 
> > @baoachun I am having the same problem. I found out that in my input tensors there are no NaN values, but there are Inf values and this is what causing the error. Do you know if in your input tensors you had Inf values?我遇到了相同的问题。我发现在我的输入张量中没有 NaN 值，但是有 Inf 值，这就是导致错误的原因。你知道在你的输入张量中是否有 Inf 值吗？
> > EDIT:  编辑：
> > I did some debug on this. Values that are Inf (for example scales in my case) cause NaN radius. However, the gaussians with NaN radius are nonetheless added as rendered gaussians (`num_rendered`) since there is no check for NaNs in [`preprocess`](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/rasterizer_impl.cu#L248). Next, we will reallocate `num_rendered` **uninitialized** memory for the `binningState` object.我对此进行了调试。值为 Inf（例如，在我的情况下是比例）会导致 NaN 半径。然而，由于在 `preprocess` 中没有检查 NaN，具有 NaN 半径的高斯函数仍然被添加为渲染的高斯函数（ `num_rendered` ）。接下来，我们将为 `binningState` 对象重新分配 `num_rendered` 未初始化的内存。
> > When duplicating keys, we iterate over [all gaussians with positive radius](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/rasterizer_impl.cu#L85) and assign values to the keys and values arrays which are arrays of `num_rendered` size from `binningState`. Remember that NaN gaussians **are rendered gaussians** but they don't get any key/value because their radii is not positive and thus, **their key and value are never assigned: their values come from uninitialized memory**. This causes the illegal memory access in some cases. This is why the error occurs randomly, because unitialized memory is unpredictable and can have any value at any time.当复制键时，我们遍历所有具有正半径的高斯函数，并将值分配给键和值数组，这些数组是从 `binningState` 开始的 `num_rendered` 大小的数组。记住，NaN 高斯函数是渲染的高斯函数，但它们不会获得任何键/值，因为它们的半径不是正的，因此，它们的键和值永远不会分配：它们的值来自未初始化的内存。这导致在某些情况下发生非法内存访问。这就是为什么错误会随机发生的原因，因为未初始化的内存是不可预测的，可以在任何时候具有任何值。
> 
> This helped a lot! Apparently, you get these memory errors for a number of incorrect inputs. Notably, I created my own masks and passed values between 0 and 255 instead of 0 and 1. I didn't consider that this could be the problem until I saw your post. Thanks a lot!这帮了大忙！显然，你因为许多不正确的输入而得到这些内存错误。值得注意的是，我创建了自定义掩码，并传递了介于 0 到 255 之间的值，而不是 0 和 1。直到我看到你的帖子，我才意识到这可能是问题所在。非常感谢！

Thank you very much. Can you share how it was done specifically

**Comment by dhbloo** [comment]
I have found that the above memory access is caused by NaN values in `my_radius`. In my case, I am passing precomputed cov3D instead of separate scaling and rotation, and there are sometimes negative values in the diagonal of the 3x3 covariance matrix, which causes sqrt() to get a negative number as input.

**Comment by seung0h** [comment]
I just checked the device of all input tensors, including the projection matrix, and I solved this issue even though I faced the totally same problem as mentioned in this post.

**Comment by pyh3552** [comment]
> Perhaps check `my_radius`. Replacing the `float my_radius = ceil(...)` with `int my_radius = max(ceil(...), 1)` might help.


`int my_radius = max(ceil(3.f * sqrt(max(lambda1, lambda2))), 1.f);`
It works. Thank you!

**Comment by BitCalSaul** [comment]
> > Perhaps check `my_radius`. Replacing the `float my_radius = ceil(...)` with `int my_radius = max(ceil(...), 1)` might help.
> 
> `int my_radius = max(ceil(3.f * sqrt(max(lambda1, lambda2))), 1.f);` It works. Thank you!

does it still work? I tried but still illegal memory access.
