### ISSUE TITLE
Cuda out of memory when calling the distCUDA2

### ISSUE THREAD

**Issue by moonagic** [graphdeco-inria/gaussian-splatting#961]
```
dist2 = torch.clamp_min(distCUDA2(torch.from_numpy(np.asarray(pcd.points)).float().cuda()), 0.0000001)
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory
```

My graphics card is RTX8000 with 48GB of memory. I also looked at #740, reconfigured the environment, and the problem persists.

**Comment by GOZIHUATANEJO** [comment]
May I ask if you have solved it now, I had the same problem as you did

**Comment by moonagic** [comment]
> May I ask if you have solved it now, I had the same problem as you did

I didn't find a direct solution. Switching my graphics card to RTX 4090 resolved the issue. I suspect the RTX 8000 (and possibly other cards in that series) is either unsupported or requires additional configuration.

**Comment by thegenerativegeneration** [comment]
Hey, the problem for me was that I had set the cuda architecture wrong (in docker).
Make sure TORCH_CUDA_ARCH_LIST [includes the architecture of your GPU ](https://stackoverflow.com/a/74962874)(e.g. TORCH_CUDA_ARCH_LIST="8.0 8.6 8.7 8.9" should work with GPUs from 3xxx and 4xxx).
